#Disables certain types. Note that all these configs, like in any other mod, only hide stuff from tabs and disable their recipes
[types]

		[types.wood_type.ars_nouveau]
			archwood = true

		[types.wood_type.silentgear]
			netherwood = true

		[types.wood_type.integrateddynamics]
			menril = true

		[types.wood_type.aether]
			skyroot = true

		[types.wood_type.deep_aether]
			roseroot = true
			yagroot = true
			cruderoot = true
			conberry = true
			sunroot = true

		[types.wood_type.deeperdarker]
			echo = true

		[types.leaves_type.ars_nouveau]
			blue_archwood = true
			green_archwood = true
			purple_archwood = true
			red_archwood = true

		[types.leaves_type.silentgear]
			netherwood = true

		[types.leaves_type.integrateddynamics]
			menril = true

		[types.leaves_type.occultism]
			otherworld = true

		[types.leaves_type.aether]
			skyroot = true
			golden_oak = true
			crystal = true
			crystal_fruit = true
			holiday = true
			decorated_holiday = true

		[types.leaves_type.deep_aether]
			roseroot = true
			flowering_roseroot = true
			blue_roseroot = true
			flowering_blue_roseroot = true
			yagroot = true
			cruderoot = true
			conberry = true
			sunroot = true

		[types.leaves_type.deeperdarker]
			echo = true

#Disables specific entries
[entries]

		[entries.wood_type.farmersdelight]
			cabinet = true

		[entries.wood_type.functionalstorage]
			1 = true
			4 = true
			2 = true
