#The height of kelp to be able to grow.
# Default: 40
# Range: > 25
kelpHeight = 40
#The amount of power required by the mixer each tick.
# Default: 10
# Range: > 0
mixerPowerRequirement = 10
#The amount of power required by the Augmentation Station each tick.
# Default: 25
# Range: > 0
augmentationPowerRequirement = 25
#The amount of power required by the Deep Sea Drain each tick.
# Default: 20
# Range: > 0
drainPowerRequirement = 20
#The distance of normals lasers.
# Default: 16
# Range: 0 ~ 128
laserDistance = 16
#The distance of Long Distance Laser lasers.
# Default: 64
# Range: 0 ~ 128
longDistanceLaserDistance = 64
#The capacity of the Mixers Input Tank
# Default: 1000
# Range: > 0
mixerInputCapacity = 1000
#The capacity of the Mixers Output Tank
# Default: 1000
# Range: > 0
mixerOutputCapacity = 1000
#The amount of salt water collected by the Deep Sea Drain each second (mb)
# Default: 500
# Range: > 0
drainSaltWaterAmount = 500
#The fluid capacity of the Deep Sea Drain
# Default: 128000
# Range: > 0
drainCapacity = 128000
#Determines whether to give the player a book when joining a new world
spawnBookInInventory = true
#Determines whether the player should be able to collect salt water when picking up water in an ocean biome
collectSaltWater = true
#Determines whether the player should be able to collect pressurized air bottles by right-clicking on a bubble column
collectAirWithBottle = true
#The amount of damage the guardian augments laser deals
# Default: 3
# Range: > 0
guardianAugmentDamage = 3
